"use client";

import React from "react";
import { Card } from "@douyinfe/semi-ui";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T17:25:40.683634
// Source: unknown
// Based on: Semi Design System

export interface CardProps {
  variant?: string;
  padding?: string;
  children: React.ReactNode;
}

export const Card = React.forwardRef<
  any,
  CardProps
>((variant, padding, children, className, ...props}, ref) => {
  return (
    <Card
      ref={ref}
      className={className}
      style={{}}
      {...props}
    >
      {children}
    </Card>
  );
}});

Card.displayName = "Card";