"use client";

import React from "react";
import { Tag } from "@douyinfe/semi-ui";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T17:25:40.683648
// Source: unknown
// Based on: Semi Design System

export interface BadgeProps {
  variant?: string;
  children: React.ReactNode;
}

export const Badge = React.forwardRef<
  any,
  BadgeProps
>((variant, children, className, ...props}, ref) => {
  return (
    <Tag
      ref={ref}
      className={className}
      style={{}}
      {...props}
    >
      {children}
    </Tag>
  );
}});

Badge.displayName = "Badge";