"use client";

import React from "react";
import { Button } from "@douyinfe/semi-ui";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T17:25:40.683615
// Source: unknown
// Based on: Semi Design System

export interface ButtonProps {
  variant?: string;
  size?: string;
  disabled?: boolean;
  loading?: boolean;
  children: React.ReactNode;
}

export const Button = React.forwardRef<
  any,
  ButtonProps
>((variant, size, disabled, loading, children, className, ...props}, ref) => {
  return (
    <Button
      ref={ref}
      className={className}
      style={{}}
      {...props}
    >
      {children}
    </Button>
  );
}});

Button.displayName = "Button";