"use client";

import React from "react";
import { Input } from "@douyinfe/semi-ui";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T17:25:40.683644
// Source: unknown
// Based on: Semi Design System

export interface InputProps {
  variant?: string;
  size?: string;
  disabled?: boolean;
  placeholder?: string;
  value?: string;
  onChange?: (value: string) => void;
}

export const Input = React.forwardRef<
  any,
  InputProps
>((variant, size, disabled, placeholder, value, onChange, className, ...props}, ref) => {
  return (
    <Input
      ref={ref}
      className={className}
      style={{}}
      {...props}
    >
      {children}
    </Input>
  );
}});

Input.displayName = "Input";